### ISSUE TITLE
UX comparison between on-change and some debounce period after typing

### ISSUE THREAD

**Issue by dsmurrell** [Code-Pop/validating-vue3-forms#2]
Hi

This is related to the last lesson of your course in validation: https://www.vuemastery.com/courses/validating-vue3-forms/lazy-validation

Currently I have some of my forms implemented such that the validation error messages appear not when focus is lost but when the user hasn't typed a character after say 1 or 2 seconds.

Is this any better UX wise than having the errors appear on change?

**Comment by marina-mosti** [comment]
Some users may take longer to type due to accessibility issues, I would say the blur approach is preferable overall :)

**Comment by dsmurrell** [comment]
Thank you!
